import Link from 'next/link';
import { ArrowRight, BookOpen, BrainCircuit, FileText, HeartPulse, LayoutDashboard, LibraryBig, PenLine, ShieldCheck, Stethoscope } from 'lucide-react';
import { currentUser } from '@/lib/auth';
import { isAdmin } from '@/lib/admin';

const highlights = [
  { icon: BookOpen, title: 'Clinical learning library', text: 'Explore 150 publications, 150 practical articles, and 100 structured ECG case studies.' },
  { icon: BrainCircuit, title: 'AI learning support', text: 'Generate educational article drafts or ask the floating AI Tutor about any selected concept.' },
  { icon: FileText, title: 'Free author publishing', text: 'Create an account, submit a complete manuscript, and track its editorial progress.' },
];

const workspaceLinks = [
  { href: '/publications', icon: LibraryBig, label: 'Publications', detail: 'Research reviews & case studies', accent: 'from-[#0f8078] to-[#064b61]' },
  { href: '/articles', icon: BookOpen, label: 'Articles', detail: 'Practical clinical learning', accent: 'from-[#176476] to-[#0b2031]' },
  { href: '/ecg', icon: HeartPulse, label: 'ECG cases', detail: '100 guided interpretations', accent: 'from-[#1c7f76] to-[#176476]' },
  { href: '/ai-tools', icon: BrainCircuit, label: 'AI tools', detail: 'Draft, clarify, and learn', accent: 'from-[#795d99] to-[#294a75]' },
  { href: '/publish', icon: PenLine, label: 'Publish with us', detail: 'Free editorial submission', accent: 'from-[#a36f35] to-[#705025]' },
  { href: '/topics', icon: Stethoscope, label: 'Topics', detail: 'Find your learning focus', accent: 'from-[#0d766f] to-[#174a5e]' },
];

function PublicWelcome() {
  return <>
    <section className="relative overflow-hidden bg-[#071a29] px-5 py-24 text-white md:py-32"><div className="absolute -right-20 -top-24 h-96 w-96 rounded-full border border-teal/30" /><div className="absolute -bottom-44 left-1/3 h-96 w-96 rounded-full bg-teal/10 blur-3xl" /><div className="relative mx-auto max-w-6xl"><p className="eyebrow text-teal-300">Welcome to Hum Medicals</p><div className="mt-7 grid items-end gap-12 lg:grid-cols-[1.25fr_.75fr]"><div><h1 className="max-w-4xl text-5xl leading-[1.04] text-white md:text-7xl">A clearer place to <em className="font-normal text-teal-300">learn</em>, publish, and grow.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Hum Medicals brings clinical learning, ECG practice, medical writing, and free manuscript submission into one thoughtful workspace for students and healthcare professionals.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/sign-up" className="inline-flex items-center gap-2 bg-teal px-6 py-3.5 text-sm font-bold text-white transition hover:bg-teal-600">Get started <ArrowRight size={16} /></Link><Link href="/sign-in" className="border border-white/30 px-6 py-3.5 text-sm font-bold text-white transition hover:border-teal-300 hover:text-teal-300">Sign in</Link></div><p className="mt-5 text-sm text-slate-400">Create a free account to access the Hum Medicals workspace.</p></div><aside className="border border-teal/30 bg-white/5 p-7 backdrop-blur"><p className="eyebrow text-teal-300">Your journey</p><ol className="mt-7 grid gap-5"><li className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-teal text-xs font-bold">1</span><div><p className="font-bold">Create your free account</p><p className="mt-1 text-sm leading-6 text-slate-300">Secure access to your author workspace and submissions.</p></div></li><li className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-teal text-xs font-bold text-teal-300">2</span><div><p className="font-bold">Explore and learn</p><p className="mt-1 text-sm leading-6 text-slate-300">Use focused resources, ECG cases, and AI learning support.</p></div></li><li className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-teal text-xs font-bold text-teal-300">3</span><div><p className="font-bold">Share your work</p><p className="mt-1 text-sm leading-6 text-slate-300">Submit a complete paper free of charge for editorial review.</p></div></li></ol></aside></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-24"><div className="max-w-2xl"><p className="eyebrow">Website overview</p><h2 className="section-title">Everything you need for a more deliberate learning practice.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{highlights.map(({ icon: Icon, title, text }) => <article key={title} className="paper-panel p-7"><Icon className="text-teal" size={26} /><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{text}</p></article>)}</div></section>
    <section className="border-y border-[#dce2e1] bg-[#eef2f1] px-5 py-20 dark:bg-slate-900"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-8"><div><p className="eyebrow">Ready when you are</p><h2 className="mt-3 font-serif text-4xl leading-tight">Begin with a free Hum Medicals account.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">There are no publishing fees, payment steps, or subscription charges for authors.</p></div><Link href="/sign-up" className="inline-flex items-center gap-2 bg-[#0b2031] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-teal">Create free account <ShieldCheck size={16} /></Link></div></section>
  </>;
}

function MemberHome({ name, admin }: { name: string; admin: boolean }) {
  return <>
    <section className="member-home-hero relative overflow-hidden bg-[#071a29] px-5 py-16 text-white md:py-20"><div className="member-orb member-orb-one" /><div className="member-orb member-orb-two" /><div className="relative mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="eyebrow text-teal-300">Hum Medicals workspace</p><h1 className="mt-3 max-w-3xl text-5xl leading-[1.04] text-white md:text-6xl">Welcome back, {name.split(' ')[0]}.<br /><em className="font-normal text-teal-300">Where would you like to begin?</em></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Your clinical learning library, author workspace, and AI study support are all one step away.</p></div><div className="member-hero-stat"><span className="text-4xl font-serif">400+</span><span className="text-xs font-bold uppercase tracking-[.16em] text-teal-200">Learning resources</span></div></div><div className="mt-12 flex flex-wrap gap-3"><Link href="/publications" className="premium-button bg-teal">Explore publications <ArrowRight className="ml-2" size={16} /></Link><Link href="/ai-tools" className="member-ghost-button">Open AI tools <BrainCircuit className="ml-2" size={16} /></Link><Link href="/publish" className="member-ghost-button">Submit your work <PenLine className="ml-2" size={16} /></Link>{admin && <Link href="/admin" className="member-admin-button">Editorial dashboard <LayoutDashboard className="ml-2" size={16} /></Link>}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your clinical workspace</p><h2 className="section-title">Every part of Hum Medicals, within reach.</h2></div><Link href="/account" className="text-sm font-bold text-teal hover:text-[#0b2031]">Open my account <ArrowRight className="inline" size={15} /></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{workspaceLinks.map(({ href, icon: Icon, label, detail, accent }, index) => <Link href={href} key={href} className="workspace-link-card group" style={{ '--card-index': index } as React.CSSProperties}><div className={`workspace-link-icon bg-gradient-to-br ${accent}`}><Icon size={24} /></div><div><h3 className="font-serif text-2xl">{label}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{detail}</p></div><ArrowRight className="workspace-link-arrow" size={19} /></Link>)}</div></section>
    <section className="border-y border-[#dce2e1] bg-[#eef2f1] px-5 py-16 dark:bg-slate-900"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3"><Link href="/ai-tools" className="home-feature-card lg:col-span-2"><BrainCircuit className="text-teal" size={27} /><p className="eyebrow mt-8">Intelligent study support</p><h2 className="mt-3 font-serif text-4xl">Draft, clarify, and learn with an AI assistant built for clinical education.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">Use the article generator, or open the movable tutor from any page to ask about selected text and clinical concepts.</p><span className="mt-7 inline-flex items-center text-sm font-bold text-teal">Open AI tools <ArrowRight className="ml-2" size={16} /></span></Link><Link href="/publish" className="home-feature-card home-feature-dark"><PenLine className="text-teal-300" size={27} /><p className="eyebrow mt-8 text-teal-300">Author pathway</p><h2 className="mt-3 font-serif text-3xl text-white">Share your research, free of charge.</h2><p className="mt-4 text-sm leading-7 text-slate-300">Submit work, follow the review status, and see approved work take its place in the journal.</p><span className="mt-7 inline-flex items-center text-sm font-bold text-teal-300">Start a submission <ArrowRight className="ml-2" size={16} /></span></Link></div></section>
  </>;
}

export default async function Home() {
  const user = await currentUser();
  return user ? <MemberHome name={user.name} admin={isAdmin(user)} /> : <PublicWelcome />;
}
