'use client';
import { useState } from 'react';

export function NewsletterForm(){
  const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();if(!/^\S+@\S+\.\S+$/.test(email)){setMessage('Enter a valid email address.');return;}setBusy(true);setMessage('');try{const response=await fetch('/api/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const result=await response.json();setMessage(result.message||'Unable to subscribe right now.');if(response.ok)setEmail('');}catch{setMessage('Unable to subscribe right now.');}finally{setBusy(false);}}
  return <form onSubmit={submit} className="relative flex max-w-xl flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="email">Email address</label><input id="email" value={email} onChange={event=>setEmail(event.target.value)} className="min-w-0 flex-1 border border-white/25 bg-white px-4 py-3.5 text-sm text-slate-900 outline-none" placeholder="Email address" type="email" required/><button disabled={busy} className="bg-[#0b2031] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#143b55] disabled:opacity-50">{busy?'Subscribing...':'Subscribe'}</button>{message&&<p role="status" className="absolute -bottom-12 text-sm leading-5">{message}</p>}</form>;
}

export function ContactForm(){
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage('');const fields=new FormData(form);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields.get('name'),email:fields.get('email'),subject:fields.get('subject'),message:fields.get('message')})});const result=await response.json();setMessage(result.message||'Unable to send your message right now.');if(response.ok){form.reset();if(result.mailto)window.location.href=result.mailto;}}catch{setMessage('Unable to send your message right now.');}finally{setBusy(false);}}
  return <form onSubmit={submit} className="paper-panel grid gap-4 p-6 md:p-8"><input name="name" required minLength={2} aria-label="Name" className="premium-input" placeholder="Your name"/><input name="email" required type="email" aria-label="Email" className="premium-input" placeholder="Email address"/><input name="subject" required minLength={3} maxLength={180} aria-label="Subject" className="premium-input" placeholder="Subject"/><textarea name="message" required minLength={10} maxLength={5000} aria-label="Message" rows={6} className="premium-input" placeholder="How can we help?"/><button disabled={busy} className="premium-button w-fit disabled:opacity-50">{busy?'Sending...':'Send message'}</button>{message&&<p role="status" className="text-sm text-teal">{message}</p>}</form>;
}
