export type ContentItem = {
  slug: string; title: string; author: string; date: string; topic: string;
  type: string; abstract: string; body: string; tags: string[]; references: string[];
  collection: 'paper' | 'article'; pdf?: string;
};

type TopicSource = { topic: string; publications: string[]; articles: string[]; focus: string; references: string[] };

const sources: TopicSource[] = [
  { topic: 'Cardiology', focus: 'cardiovascular assessment, diagnosis, and evidence-informed management', references: ['Gulati M, et al. 2021 AHA/ACC Guideline for the Evaluation and Diagnosis of Chest Pain. Circulation. 2021.', 'Byrne RA, et al. 2023 ESC Guidelines for the Management of Acute Coronary Syndromes. Eur Heart J. 2023.'], publications: ['A Structured Review of Acute Chest Pain Risk Assessment','ST-Segment Elevation: Territory, Time, and Team Response','Interpreting Troponin Beyond a Single Value','The Clinical Logic of Heart Failure Phenotyping','A Practical Review of Atrial Fibrillation Rate and Rhythm Strategy','Hypertension Assessment: From Measurement to Meaningful Risk','Valvular Heart Disease: A Focused Clinical Review','Secondary Prevention After Myocardial Infarction','The Cardiovascular Examination in a Breathless Patient','Cardiometabolic Risk in Everyday Clinical Practice'], articles: ['How to Present a Chest-Pain History on Rounds','A Five-Minute Framework for Reading a 12-Lead ECG','What a Rising Troponin Can—and Cannot—Tell You','Heart Failure Notes: Finding the Clinical Story','Questions to Ask Before Calling a Rhythm Irregular','Blood Pressure Measurement: Common Errors That Matter','Listening for Murmurs With a Purpose','Medication Reconciliation After an Acute Coronary Syndrome','The Peripheral Clues in a Cardiac Examination','A Student Guide to Cardiovascular Risk Conversations'] },
  { topic: 'Echocardiography', focus: 'image acquisition, measurement quality, and integrated echocardiographic interpretation', references: ['Nagueh SF, et al. Recommendations for the Evaluation of Left Ventricular Diastolic Function by Echocardiography. J Am Soc Echocardiogr. 2016.', 'Zoghbi WA, et al. Recommendations for Noninvasive Evaluation of Native Valvular Regurgitation. J Am Soc Echocardiogr. 2017.'], publications: ['A Practical Approach to Left-Ventricular Diastolic Assessment','Image Optimization Before Interpretation','Quantifying Left-Ventricular Systolic Function in Context','Right-Heart Assessment: A Systematic Echo Review','Mitral Regurgitation: Integrating Qualitative and Quantitative Findings','Aortic Stenosis: Reconciling Discordant Measurements','Pericardial Effusion and Tamponade Physiology on Echo','Left-Atrial Volume: Why It Belongs in the Report','Focused Echo in Dyspnea: A Clinical Integration Guide','Quality Assurance in Basic Transthoracic Echocardiography'], articles: ['How to Read an Echocardiography Report Without Missing the Story','A Beginner’s Sequence for the Parasternal Long-Axis View','Why Ejection Fraction Is Not the Whole Ventricular Story','The Echo Findings That Suggest Right-Heart Pressure Load','A Clear Way to Describe Valve Regurgitation','When Aortic-Stenosis Numbers Do Not Agree','A Bedside Checklist for Pericardial Fluid','Left-Atrial Size: A Small Measurement With Big Context','Using Echo Clues in Acute Breathlessness','Three Image-Quality Habits to Build Early'] },
  { topic: 'Critical Care', focus: 'early recognition of instability, hemodynamic reasoning, and safe reassessment in acute care', references: ['Evans L, et al. Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2021. Intensive Care Med. 2021.', 'Vincent JL, De Backer D. Circulatory Shock. N Engl J Med. 2013.'], publications: ['Focused Echocardiography in Undifferentiated Shock','A Clinical Framework for Early Sepsis Recognition','Oxygen Delivery and the Physiology of Tissue Hypoperfusion','Vasopressor Selection: Principles for the Bedside Learner','Acute Pulmonary Edema: Immediate Assessment and Priorities','Interpreting Lactate During Resuscitation','Fluid Responsiveness: Concepts, Limits, and Communication','A Review of Acute Right-Ventricular Failure','Post-Intubation Hemodynamic Deterioration','Structured Reassessment During the First Hour of Shock'], articles: ['The First Questions in an Unstable Patient','Sepsis Screening: Turning Observations Into Escalation','A Simple Mental Model for Oxygen Delivery','What to Watch When Starting a Vasopressor','Breathlessness With Crackles: A Focused Acute-Care Approach','Lactate Trends Without Overinterpretation','Why More Fluid Is Not Always the Answer','Recognizing a Strained Right Ventricle at the Bedside','Before and After Intubation: A Safety Pause','How to Give a Clear Shock Handover'] },
  { topic: 'Clinical Medicine', focus: 'structured clinical reasoning, examination, documentation, and patient-centred decision-making', references: ['Bickley LS. Bates’ Guide to Physical Examination and History Taking. 13th ed. Wolters Kluwer; 2021.', 'Sackett DL, et al. Evidence Based Medicine: What it is and what it is not. BMJ. 1996.'], publications: ['Clinical Reasoning Under Uncertainty: A Practical Review','The Problem Representation: Turning Data Into a Diagnostic Question','A Systematic Approach to Dyspnea','Safe Clinical Handover: Structure and Situational Awareness','Medication History Taking in Complex Care','The Focused Neurological Examination for Non-Neurologists','Documenting Differential Diagnosis With Clarity','Recognizing Red Flags in Common Presentations','The Role of Serial Examination in Acute Medicine','Evidence Appraisal for the Busy Clinical Learner'], articles: ['How to Build a Useful Problem Representation','Turning a Long History Into a Focused Summary','A Ward-Based Approach to New Breathlessness','The Handover Details That Prevent Missed Care','Five Medication Questions Worth Asking Every Time','A Calm Sequence for a Focused Neurological Screen','Writing a Differential That Shows Your Thinking','Red Flags Are Prompts, Not Diagnoses','Why the Second Examination Often Matters','Reading a Clinical Paper Without Getting Lost'] },
  { topic: 'Preventive Cardiology', focus: 'risk communication, lifestyle medicine, prevention planning, and long-term cardiovascular health', references: ['Visseren FLJ, et al. 2021 ESC Guidelines on Cardiovascular Disease Prevention. Eur Heart J. 2021.', 'Grundy SM, et al. 2018 AHA/ACC Guideline on the Management of Blood Cholesterol. Circulation. 2019.'], publications: ['Cardiovascular Risk Estimation: A Patient-Centred Review','Lipid Management: Interpreting the Prevention Conversation','Physical Activity Prescription for Cardiovascular Health','Smoking Cessation as Cardiovascular Care','Diabetes and Cardiovascular Risk: Clinical Priorities','Dietary Patterns and Heart Health: An Evidence Review','Family History in Preventive Cardiology','Blood Pressure Control Beyond the Clinic Reading','Cardiac Rehabilitation: Participation and Outcomes','Communicating Absolute Risk Without Creating Fear'], articles: ['How to Explain Risk Without Overwhelming a Patient','A Practical Way to Discuss Cholesterol Results','Making Physical-Activity Advice Specific','The First Minute of a Smoking-Cessation Conversation','Diabetes Reviews With the Heart in Mind','Talking About Food Patterns, Not Perfect Diets','When Family History Changes the Conversation','Home Blood-Pressure Logs: What to Look For','How to Encourage Cardiac-Rehabilitation Attendance','Numbers, Benefits, and Shared Decisions'] }
];

export const topics = sources.map(({ topic }) => topic);
const types = ['Research Summary', 'Review Article', 'Case Study', 'Educational Guide'];
const publicationDates = ['July 4, 2026', 'June 26, 2026', 'June 12, 2026', 'May 29, 2026', 'May 15, 2026', 'May 1, 2026', 'April 17, 2026', 'April 3, 2026', 'March 20, 2026', 'March 6, 2026'];

function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }
function bodyFor(title: string, source: TopicSource, collection: 'paper' | 'article') {
  const label = collection === 'paper' ? 'publication' : 'learning article';
  return `## Clinical focus\n\n${title} examines ${source.focus}. This ${label} is written for learners who need a disciplined way to connect patient presentation, bedside findings, investigations, and the next safe clinical step. It supports education and supervised practice; it does not replace local protocols, senior review, or patient-specific clinical judgment.\n\n## A structured approach\n\nBegin by defining the immediate clinical question and identifying instability, time-critical features, and missing information. Collect data methodically, check its quality, and interpret each finding in relation to the patient’s symptoms, physiology, comorbidity, and trajectory. Avoid making a decision from a single measurement or isolated image.\n\n## Applying the evidence\n\nUse contemporary guidance as a framework rather than a substitute for reasoning. Explain what supports the leading interpretation, what remains uncertain, and which result or reassessment would change the plan. In teaching settings, this makes clinical thinking visible and helps the team communicate safely.\n\n## Practical learning points\n\n- Prioritise urgent threats before refining the differential diagnosis.\n- Use a reproducible sequence so important findings are less likely to be missed.\n- Correlate tests with history, examination, and serial change.\n- Escalate early when the patient, finding, or context exceeds the limits of the assessment.\n\n## Documentation and follow-up\n\nRecord the key findings, your interpretation, limitations, and a clear reassessment plan. Good documentation distinguishes observed facts from clinical inference and names the clinical team responsible for the next decision. Revisit the working diagnosis when new information becomes available.`;
}

function createItems(collection: 'paper' | 'article'): ContentItem[] {
  return sources.flatMap((source, sourceIndex) => {
    const titles = collection === 'paper' ? source.publications : source.articles;
    const expandedTitles = [...titles, ...titles.map((title) => 'Clinical Application: ' + title), ...titles.map((title) => 'Quality and Safety Review: ' + title)];
    return expandedTitles.map((title, index) => ({
      slug: `${collection === 'paper' ? 'publication' : 'article'}-${slugify(title)}`,
      title,
      author: collection === 'paper' ? 'Hum Medicals Editorial Team' : 'Hum Medicals',
      date: publicationDates[index % publicationDates.length],
      topic: source.topic,
      type: collection === 'paper' ? types[(index + sourceIndex) % types.length] : ['Clinical Primer', 'Practice Note', 'Learning Guide', 'Ward Round Brief'][index % 4],
      abstract: `${title} offers an evidence-informed, clinically practical guide to ${source.focus}, with a clear sequence for interpretation, communication, and reassessment.`,
      body: bodyFor(title, source, collection),
      tags: [source.topic, collection === 'paper' ? 'Evidence-based education' : 'Clinical learning', 'Professional development'],
      references: source.references,
      collection
    }));
  });
}

const papers = createItems('paper');
const articles = createItems('article');
export const getAll = (kind: 'paper' | 'article') => kind === 'paper' ? papers : articles;
export const getOne = (kind: 'paper' | 'article', slug: string) => getAll(kind).find((item) => item.slug === slug);
export const related = (topic: string) => [...papers, ...articles].filter((item) => item.topic === topic);

