export type EcgCase = { slug:string; number:number; title:string; category:string; difficulty:'Foundation'|'Intermediate'|'Advanced'; summary:string; presentation:string; findings:string[]; differential:string[]; keyPoint:string; body:string; references:string[] };
type Base = Omit<EcgCase,'slug'|'number'|'difficulty'|'summary'|'body'>;
const bases: Base[] = [
{title:'Atrial Fibrillation With Rapid Ventricular Response',category:'Rhythm',presentation:'A patient presents with palpitations and exertional breathlessness; the rhythm strip is irregularly irregular.',findings:['No consistent P waves','Irregular R–R intervals','Rapid ventricular rate'],differential:['Atrial flutter with variable block','Multifocal atrial tachycardia'],keyPoint:'Confirm rhythm, assess stability, and avoid treating the tracing without the clinical context.',references:['Hindricks G, et al. 2020 ESC Guidelines for Atrial Fibrillation. Eur Heart J. 2021.']},
{title:'Typical Atrial Flutter With 2:1 Conduction',category:'Rhythm',presentation:'A patient has a regular narrow-complex tachycardia close to 150 beats per minute.',findings:['Regular ventricular rate near 150 bpm','Flutter activity may be clearest in inferior leads','Atrial activity can be hidden within QRS/T complexes'],differential:['Sinus tachycardia','AV nodal re-entry tachycardia'],keyPoint:'A rate near 150 bpm should prompt a deliberate search for flutter waves.',references:['Brugada J, et al. 2019 ESC Guidelines for Supraventricular Tachycardia. Eur Heart J. 2020.']},
{title:'Regular Narrow-Complex Tachycardia',category:'Rhythm',presentation:'A haemodynamically stable patient reports abrupt-onset palpitations with a regular narrow-complex tachycardia.',findings:['Regular narrow QRS complexes','P-wave relation requires careful inspection','Onset and offset history is informative'],differential:['AVNRT','AVRT','Atrial tachycardia'],keyPoint:'Classify stability first, then use a structured rhythm analysis before naming the mechanism.',references:['Brugada J, et al. 2019 ESC Guidelines for Supraventricular Tachycardia. Eur Heart J. 2020.']},
{title:'Wide-Complex Tachycardia: Ventricular Tachycardia Until Proven Otherwise',category:'Rhythm',presentation:'An adult with structural heart disease develops a sustained regular wide-complex tachycardia.',findings:['Broad QRS tachycardia','Look for AV dissociation or capture beats','Clinical history changes pre-test probability'],differential:['Ventricular tachycardia','SVT with aberrancy','Pre-excited tachycardia'],keyPoint:'Treat regular wide-complex tachycardia as ventricular tachycardia unless expert assessment establishes otherwise.',references:['Al-Khatib SM, et al. 2017 AHA/ACC/HRS Guideline for Ventricular Arrhythmias. Heart Rhythm. 2018.']},
{title:'Polymorphic Ventricular Tachycardia and QT Context',category:'Rhythm',presentation:'A patient with syncope has a changing-axis broad-complex tachycardia on monitoring.',findings:['Beat-to-beat QRS axis variation','Assess baseline QT interval','Review drugs and electrolytes'],differential:['Torsades de pointes','Ischaemia-related polymorphic VT'],keyPoint:'The baseline QT interval and reversible precipitants guide the immediate differential.',references:['Al-Khatib SM, et al. 2017 AHA/ACC/HRS Guideline for Ventricular Arrhythmias. Heart Rhythm. 2018.']},
{title:'Sinus Bradycardia in a Symptomatic Patient',category:'Rhythm',presentation:'A patient reports presyncope with a slow regular rhythm and visible sinus P waves.',findings:['Sinus P wave before each QRS','Slow atrial and ventricular rate','Assess medication and metabolic context'],differential:['Sinus node dysfunction','High-grade AV block'],keyPoint:'A slow rate is interpreted through symptoms, perfusion, reversible causes, and chronology.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'Premature Ventricular Complexes in a Structured Assessment',category:'Rhythm',presentation:'A patient notes intermittent skipped beats; the ECG shows early broad complexes.',findings:['Premature broad QRS complex','Compensatory pause may be present','Assess morphology and burden'],differential:['Aberrantly conducted atrial ectopy','Ventricular ectopy'],keyPoint:'Describe the ectopy accurately and place it in the context of symptoms and structural disease risk.',references:['Al-Khatib SM, et al. 2017 AHA/ACC/HRS Guideline for Ventricular Arrhythmias. Heart Rhythm. 2018.']},
{title:'Anterior ST-Elevation Myocardial Infarction Pattern',category:'Ischaemia',presentation:'A patient with ongoing chest pain has ST elevation in contiguous anterior precordial leads.',findings:['Contiguous ST elevation','Assess reciprocal changes','Compare prior ECG when available'],differential:['Acute coronary occlusion','Early repolarisation','Pericarditis'],keyPoint:'ECG interpretation must be paired with symptom onset, examination, and immediate reperfusion pathways.',references:['Byrne RA, et al. 2023 ESC Guidelines for Acute Coronary Syndromes. Eur Heart J. 2023.']},
{title:'Inferior ST-Elevation Pattern With Right-Ventricular Considerations',category:'Ischaemia',presentation:'A patient with chest discomfort has inferior ST elevation and borderline blood pressure.',findings:['ST elevation in inferior leads','Seek reciprocal changes','Consider right-sided leads when appropriate'],differential:['Inferior coronary occlusion','Pericarditis'],keyPoint:'Inferior injury patterns should trigger attention to right-ventricular involvement and haemodynamics.',references:['Byrne RA, et al. 2023 ESC Guidelines for Acute Coronary Syndromes. Eur Heart J. 2023.']},
{title:'Posterior Myocardial Injury Clues',category:'Ischaemia',presentation:'A patient has ischaemic symptoms with ST depression and tall R waves in anterior leads.',findings:['Horizontal ST depression in V1–V3','Prominent R waves may appear','Posterior leads can clarify'],differential:['Posterior injury pattern','Subendocardial ischaemia','Right-ventricular strain'],keyPoint:'Reciprocal posterior patterns are an active search task, not an incidental finding.',references:['Byrne RA, et al. 2023 ESC Guidelines for Acute Coronary Syndromes. Eur Heart J. 2023.']},
{title:'High-Risk Non-ST-Elevation Ischaemic Changes',category:'Ischaemia',presentation:'A patient with ongoing pain has dynamic ST depression and T-wave changes without ST elevation.',findings:['Dynamic ST-segment depression','Symmetric T-wave inversion may occur','Serial ECGs add information'],differential:['Non-ST-elevation acute coronary syndrome','Rate-related change','Electrolyte effect'],keyPoint:'A single ECG is a time point; serial changes and risk profile determine urgency.',references:['Byrne RA, et al. 2023 ESC Guidelines for Acute Coronary Syndromes. Eur Heart J. 2023.']},
{title:'Pericarditis Pattern Versus Myocardial Injury',category:'Ischaemia',presentation:'A patient with pleuritic chest pain has widespread ST-segment elevation.',findings:['Diffuse rather than territorial elevation','PR-segment changes may be seen','Symptoms and inflammatory context matter'],differential:['Acute pericarditis','ST-elevation myocardial infarction','Early repolarisation'],keyPoint:'Distribution, reciprocal changes, and clinical history help prevent premature closure.',references:['Adler Y, et al. 2015 ESC Guidelines for Pericardial Diseases. Eur Heart J. 2015.']},
{title:'First-Degree Atrioventricular Block',category:'Conduction',presentation:'An asymptomatic ECG has a consistently prolonged PR interval.',findings:['PR interval prolonged','Every P wave conducts','Assess associated conduction disease'],differential:['Physiologic AV delay','Medication effect','Conduction system disease'],keyPoint:'A prolonged PR interval should be measured and contextualised, not merely labelled.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'Mobitz I Second-Degree Atrioventricular Block',category:'Conduction',presentation:'A monitored patient has progressive PR prolongation before a dropped QRS complex.',findings:['Progressive PR prolongation','Non-conducted P wave','Grouped beating'],differential:['Mobitz I block','Atypical conduction pattern'],keyPoint:'Describe the sequence across several beats before assigning a block pattern.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'High-Grade Atrioventricular Block',category:'Conduction',presentation:'A patient with dizziness has multiple non-conducted P waves and a slow ventricular response.',findings:['More P waves than QRS complexes','Fixed or changing PR relationship','Bradycardia may compromise perfusion'],differential:['High-grade AV block','Complete heart block'],keyPoint:'Conduction disease with symptoms requires urgency assessment and escalation.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'Right Bundle-Branch Block',category:'Conduction',presentation:'An ECG reveals a broad QRS complex with right precordial terminal forces.',findings:['QRS widening','Right precordial rSR-prime morphology may occur','Wide terminal S waves in lateral leads'],differential:['Right bundle-branch block','Right-ventricular conduction delay'],keyPoint:'State whether the pattern is new, old, complete, or incomplete when data allow.',references:['Surawicz B, et al. AHA/ACCF/HRS Recommendations for ECG Interpretation. Circulation. 2009.']},
{title:'Left Bundle-Branch Block and Ischaemia Context',category:'Conduction',presentation:'A patient with chest discomfort has a broad QRS and left bundle-branch block pattern.',findings:['Broad QRS with secondary ST-T discordance','Prior ECG comparison is valuable','Use validated criteria with context'],differential:['Chronic LBBB','Acute occlusion with LBBB'],keyPoint:'Bundle-branch block changes repolarisation; structured criteria support but do not replace clinical judgment.',references:['Byrne RA, et al. 2023 ESC Guidelines for Acute Coronary Syndromes. Eur Heart J. 2023.']},
{title:'Ventricular Paced Rhythm',category:'Pacing',presentation:'A patient with an implanted device has paced complexes on a routine tracing.',findings:['Pacing spikes may be visible','QRS morphology reflects pacing site','Capture and sensing must be assessed clinically'],differential:['Ventricular pacing','Fusion beats','Pacing malfunction'],keyPoint:'Assess rhythm, capture, symptoms, and device history rather than relying on one visual feature.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'Atrial Paced Rhythm and AV Conduction',category:'Pacing',presentation:'A paced rhythm shows atrial pacing impulses followed by conducted QRS complexes.',findings:['Atrial pacing spike precedes P wave','AV conduction may be native','Rate response can affect interpretation'],differential:['Atrial pacing','Dual-chamber pacing','Atrial undersensing'],keyPoint:'Pacing interpretation begins with identifying which chamber is paced and whether capture is present.',references:['Kusumoto FM, et al. 2018 ACC/AHA/HRS Bradycardia Guideline. Circulation. 2019.']},
{title:'Hyperkalaemia Pattern Recognition',category:'Electrolyte',presentation:'A patient with renal impairment has weakness and a changing ECG.',findings:['Peaked T waves may appear','PR prolongation and QRS widening may evolve','Severity does not always track one feature'],differential:['Hyperkalaemia','Early repolarisation','Hyperacute ischaemic T waves'],keyPoint:'Suspected potassium toxicity is a clinical emergency; obtain urgent confirmation while acting to local protocols.',references:['Weisberg LS. Management of Severe Hyperkalemia. Crit Care Med. 2008.']},
{title:'Hypokalaemia and Repolarisation Changes',category:'Electrolyte',presentation:'A patient receiving diuretics has fatigue and an ECG with repolarisation abnormalities.',findings:['T-wave flattening','Prominent U waves may be present','QT assessment may be misleading when U waves merge'],differential:['Hypokalaemia','Drug effect','Ischaemia'],keyPoint:'Electrolyte-related ECG changes should prompt medication review, measurement, and safe correction planning.',references:['Surawicz B, et al. AHA/ACCF/HRS Recommendations for ECG Interpretation. Circulation. 2009.']},
{title:'QT Prolongation and Torsades Risk',category:'Electrolyte',presentation:'A patient on multiple medicines has syncope and a prolonged corrected QT interval.',findings:['QT interval requires rate-aware interpretation','Review QT-prolonging medicines','Assess potassium, magnesium, and calcium'],differential:['Acquired long-QT syndrome','Congenital long-QT syndrome'],keyPoint:'A prolonged QT is a risk marker that requires active review of reversible causes and arrhythmic symptoms.',references:['Drew BJ, et al. Prevention of Torsade de Pointes in Hospital Settings. Circulation. 2010.']},
{title:'Left-Ventricular Hypertrophy With Strain Pattern',category:'Chamber Patterns',presentation:'A patient with longstanding hypertension has high-voltage QRS complexes and lateral repolarisation change.',findings:['Voltage criteria can support but not diagnose LVH','Lateral ST-T changes may occur','Compare with symptoms and echocardiography'],differential:['LVH with strain','Ischaemia','Bundle-branch block'],keyPoint:'Voltage is influenced by body habitus and lead placement; interpret it with the whole clinical picture.',references:['Hancock EW, et al. AHA/ACCF/HRS Recommendations for ECG Interpretation. Circulation. 2009.']},
{title:'Right-Heart Strain Pattern in Acute Illness',category:'Chamber Patterns',presentation:'An acutely breathless patient has sinus tachycardia and new right-sided ECG changes.',findings:['Sinus tachycardia is common but nonspecific','Right precordial T-wave inversion may occur','Clinical probability determines next tests'],differential:['Pulmonary embolism','Right-ventricular pressure overload','Ischaemia'],keyPoint:'ECG may raise or lower suspicion but does not establish a pulmonary vascular diagnosis alone.',references:['Konstantinides SV, et al. 2019 ESC Guidelines for Acute Pulmonary Embolism. Eur Heart J. 2020.']}
];
const variants=[['Initial Recognition','Foundation'],['Structured Interpretation','Intermediate'],['Diagnostic Pitfalls','Intermediate'],['Clinical Decision-Making','Advanced']] as const;
function slugify(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function makeBody(base:Base,variant:string){return `## Case context\n\n${base.presentation} This educational case focuses on **${base.title}** through a ${variant.toLowerCase()} lens. It is intended for structured learning and supervised clinical practice; it is not a substitute for patient-specific assessment, local protocols, or urgent senior review.\n\n## Stepwise ECG analysis\n\nStart by confirming patient identifiers, calibration, lead placement, and recording quality. Then assess rate, regularity, atrial activity, PR interval, QRS width and morphology, frontal axis, ST segments, T waves, and QT interval. Record what is observed before inferring a diagnosis.\n\n## Findings to identify\n\n${base.findings.map(item=>`- ${item}`).join('\n')}\n\n## Reasoned differential\n\n${base.differential.map(item=>`- ${item}`).join('\n')}\n\n## Clinical integration\n\nThe tracing must be interpreted alongside symptoms, haemodynamic state, medications, electrolyte status, prior ECGs, and serial change. Identify time-critical instability first. If the presentation suggests acute coronary syndrome, significant bradycardia, malignant arrhythmia, or metabolic toxicity, follow urgent escalation pathways while the interpretation is refined.\n\n## Teaching point\n\n${base.keyPoint}\n\n## Case takeaway\n\nA reliable ECG interpretation is explicit about uncertainty, documents comparison with prior data when available, and names the clinical action or reassessment that follows.`;}
export const ecgCases:EcgCase[]=bases.flatMap((base,baseIndex)=>variants.map(([variant,difficulty],variantIndex)=>{const number=baseIndex*4+variantIndex+1;const title=`ECG Case ${String(number).padStart(3,'0')}: ${base.title} — ${variant}`;return {slug:slugify(title),number,title,category:base.category,difficulty,summary:`A detailed ${difficulty.toLowerCase()} ECG case study on ${base.title.toLowerCase()}, with systematic interpretation, differential diagnosis, and clinical safety framing.`,presentation:base.presentation,findings:base.findings,differential:base.differential,keyPoint:base.keyPoint,body:makeBody(base,variant),references:base.references};}));
export const getEcgCase=(slug:string)=>ecgCases.find(item=>item.slug===slug);
export const ecgCategories=Array.from(new Set(ecgCases.map(item=>item.category)));

